branches:
  only:
    - master

sudo: true

before_cache: ci/before-cache.sh

cache:
  directories:
    # Cache the Homebrew's downloaded bottles on macOS.
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - name: GCC 5??
      os: linux
      addons:
        apt:
          sources:
            # It contains the g++-7 package.
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=gcc-5
        - CXX=g++-5
    - name: GCC 6.5
      os: linux
      addons:
        apt:
          sources:
            # It contains the g++-6 package.
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=gcc-6
        - CXX=g++-6
    - name: GCC 7.4
      os: linux
      addons:
        apt:
          sources:
            # It contains the g++-7 package.
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=gcc-7
        - CXX=g++-7

    - name: GCC 8.3
      os: linux
      addons:
        apt:
          sources:
            # It contains the g++-8 package.
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=gcc-8
        - CXX=g++-8

    - name: GCC 9.1
      os: linux
      addons:
        apt:
          sources:
            # It contains the g++-9 package.
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=gcc-9
        - CXX=g++-9

    - name: Clang 9.0
      os: linux
      before_install:
        - source ci/install-android-ndk.sh
        # It contains the g++-9 package.
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        # Add the Clang 9 repository following the instructions at https://apt.llvm.org/.
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo add-apt-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main' -y
        - sudo apt-get update
        - sudo apt-get install g++-9
        - sudo apt-get install clang-9
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./run_tests.sh
      env:
        - CC=clang-9
        - CXX=clang++-9

    - name: GCC 7.4
      os: osx
      osx_image: xcode11.2
      addons:
        homebrew:
          packages:
            - gcc@7
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=/usr/local/bin/gcc-7
        - CXX=/usr/local/bin/g++-7

    - name: GCC 8.3
      os: osx
      osx_image: xcode11.2
      addons:
        homebrew:
          packages:
            - gcc@8
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=/usr/local/bin/gcc-8
        - CXX=/usr/local/bin/g++-8

    - name: GCC 9.2
      os: osx
      osx_image: xcode11.2
      addons:
        homebrew:
          packages:
            - gcc@9
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=/usr/local/bin/gcc-9
        - CXX=/usr/local/bin/g++-9

    - name: AppleClang 8.3
      os: osx
      osx_image: xcode8.3
      addons:
        homebrew:
          packages:
            # The given CMake version is less than 3.10 so it should be updated.
            - cmake
          update: true
      before_install:
        - source ci/install-android-ndk.sh
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./build.sh --ios
        - ./run_tests.sh
      env:
        - CC=clang
        - CXX=clang++

    - name: AppleClang 9.4
      os: osx
      osx_image: xcode9.4
      before_install:
        - source ci/install-android-ndk.sh
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./build.sh --ios
        - ./run_tests.sh
      env:
        - CC=clang
        - CXX=clang++

    - name: AppleClang 10.3
      os: osx
      osx_image: xcode10.3
      before_install:
        - source ci/install-android-ndk.sh
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./build.sh --ios
        - ./run_tests.sh
      env:
        - CC=clang
        - CXX=clang++

    - name: AppleClang 11.2 + coverage
      os: osx
      osx_image: xcode11.2
      addons:
        homebrew:
          packages:
            - lcov
      before_install:
        - source ci/install-android-ndk.sh
        # Necessary to publish the coverage on coveralls.
        - gem install coveralls-lcov
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./build.sh --ios
        - ./run_tests.sh --coverage-raw
        # Publish the coverage results to Coveralls.io.
        - coveralls-lcov build/tests/out/coverage/filtered.info
      env:
        - CC=clang
        - CXX=clang++