language: cpp
compiler: clang
os: osx
osx_image: xcode10.2

# TODO: lcov only for coverage stage
addons:
  homebrew:
    packages:
      - lcov

jobs:
  include:
    # The build stage will build the library for Darwin, Android and iOS.
    - stage: build
      name: Darwin
      script: ./build.sh --darwin
    - name: Android
      script: ./build.sh --android
      env: BUILD_ANDROID=true
    - name: iOS
      script: ./build.sh --ios
    # The test stage will run all the tests and it will calculate the coverage.
    - stage: test
      name: Run all tests
      script: lcov --version; ./run_tests.sh --coverage

before_install:
  - if [[ "$BUILD_ANDROID" == "true" ]]; then
    curl https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip -o ndk-r20.zip;
    unzip -q ndk-r20.zip;
    export ANDROID_NDK=android-ndk-r20;
    fi