os: osx
osx_image: xcode10.2

branches:
  only:
    - master

env:
  global:
    - CC_GCC=/usr/local/bin/gcc-9
    - CXX_GCC=/usr/local/bin/g++-9
    - CC_CLANG=clang
    - CXX_CLANG=clang++

jobs:
  include:
    # The build stage will build the library for Darwin, Android and iOS.
    - stage: build
      name: Target=Darwin; Compiler=GCC-9
      script: ./build.sh --darwin
      addons:
        homebrew:
          packages:
            - gcc@9
      env:
        - CC=$CC_GCC
        - CXX=$CXX_GCC
    - name: Target=Darwin; Compiler=Clang-10
      script: ./build.sh --darwin
      env:
        - CC=$CC_CLANG
        - CXX=$CXX_CLANG
    # The build the library for Android the compiler is given by the NDK toolchain file.
    - name: Target=Android
      script: ./build.sh --android
      env:
        - BUILD_ANDROID=true
    # To build the library for iOS the compiler is given by Xcode.
    - name: Target=iOS
      script: ./build.sh --ios
    # The test stage will run all the tests and it will calculate the coverage.
    - stage: test
      name: Compiler=GCC-9
      script:
        - gem install coveralls-lcov
        - ./run_tests.sh --coverage-raw
        - coveralls-lcov build/tests/out/coverage/filtered.info
      env:
        - CC=$CC_GCC
        - CXX=$CXX_GCC
        - RUN_TESTS_WITH_COVERAGE=true
    - stage: test
      name: Compiler=Clang-10
      script:
        - gem install coveralls-lcov
        - ./run_tests.sh --coverage-raw
        - coveralls-lcov build/tests/out/coverage/filtered.info
      env:
        - CC=$CC_CLANG
        - CXX=$CXX_CLANG
        - RUN_TESTS_WITH_COVERAGE=true

before_install:
  # The Android NDK toolchain file is needed to build the library for Android so, before building, Travis will download
  # the NDK R20, unzip them and export their path to use it inside the build script.
  - if [[ "$BUILD_ANDROID" == "true" ]]; then
    curl https://dl.google.com/android/repository/android-ndk-r20-darwin-x86_64.zip -o ndk-r20.zip;
    unzip -q ndk-r20.zip;
    export ANDROID_NDK=android-ndk-r20;
    fi
  # Install GCC if needed.
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CC" == "$CC_GCC" ]]; then
   # brew install gcc;
    #fi

install:
  # Install LCOV only when the tests are run with coverage.
  # This is optimal since we don't want to install it in jobs which don't use it.
  - if [[ "$RUN_TESTS_WITH_COVERAGE" == "true" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install lcov;
    else
    echo "Only OSX is supported";
    exit 1;
    fi
    fi
