branches:
  only:
    - master

sudo: true

before_cache: ci/before-cache.sh

cache:
  directories:
    # For Homebrew's formulae on macOS.
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - name: GCC 9.1
      os: linux
      addons:
        apt:
          sources:
            # It contains the g++-9 package.
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=gcc-9
        - CXX=g++-9

    - name: Clang 9.0
      os: linux
      before_install:
        - source ci/install-android-ndk.sh
        # It contains the g++-9 package.
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        # Add the Clang 9 repository following the instructions at https://apt.llvm.org/.
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - sudo add-apt-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main' -y
        - sudo apt-get update
        - sudo apt-get install g++-9
        - sudo apt-get install clang-9
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./run_tests.sh
      env:
        - CC=clang-9
        - CXX=clang++-9

    - name: GCC 9.2
      os: osx
      osx_image: xcode11
      before_install:
        - ci/brew-to-latest.sh gcc
      script:
        - ./build.sh --system
        - ./run_tests.sh
      env:
        - CC=/usr/local/bin/gcc-9
        - CXX=/usr/local/bin/g++-9

    - name: AppleClang 11.0 + coverage
      os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
            # Not needed to update Homebrew for LCOV.
            - lcov
      before_install:
        - source ci/install-android-ndk.sh
        # Necessary to publish the coverage on coveralls.
        - gem install coveralls-lcov
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./build.sh --ios
        - ./run_tests.sh --coverage-raw
        # Publish the coverage results to Coveralls.io.
        - coveralls-lcov build/tests/out/coverage/filtered.info
      env:
        - CC=clang
        - CXX=clang++