branches:
  only:
    - master

sudo: true

env:
  global:
    - CC_GCC_OSX=/usr/local/bin/gcc-9
    - CXX_GCC_OSX=/usr/local/bin/g++-9
    - CC_GCC_LINUX=gcc-9
    - CXX_GCC_LINUX=g++-9
    - CC_CLANG_OSX=clang
    - CXX_CLANG_OSX=clang++
    - CC_CLANG_LINUX=clang-9
    - CXX_CLANG_LINUX=clang++-9
    - OSX_IMAGE=xcode11

before_cache: ci/before-cache.sh

cache:
  directories:
    # For Homebrew's formulae on macOS.
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    # The build stage will build the library for the source OS, Android and iOS.
    - name: OS = macOS | Compiler = GCC 9.2
      os: osx
      osx_image: xcode11
      script:
        - ./build.sh --system
        - ./run-tests.sh
      env:
        - CC=$CC_GCC_OSX
        - CXX=$CXX_GCC_OSX

    - name: OS = macOS | Compiler = AppleClang 11.0
      os: osx
      osx_image: xcode11
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./build.sh --ios
        - ./run-tests.sh --coverage-raw
        # Publish the coverage results to Coveralls.io.
        - coveralls-lcov build/tests/out/coverage/filtered.info
      env:
        - CC=$CC_CLANG_OSX
        - CXX=$CXX_CLANG_OSX
        - BUILD_ANDROID=true
        - RUN_TESTS_WITH_COVERAGE=true

    - name: OS = Linux | Compiler = GCC 9.1
      os: linux
      script:
        - ./build.sh --system
        - ./run-tests.sh
      env:
        - CC=$CC_GCC_LINUX
        - CXX=$CXX_GCC_LINUX

    - name: OS = Linux | Compiler = Clang 9.0
      os: linux
      script:
        - ./build.sh --system
        - ./build.sh --android
        - ./run-tests.sh
      env:
        - CC=$CC_CLANG_LINUX
        - CXX=$CXX_CLANG_LINUX
        - BUILD_ANDROID=true

before_install: source ci/before-install.sh

install: ci/install.sh