language: cpp
compiler: clang
os: osx
osx_image: xcode10.2

jobs:
  include:
    - stage: build
      script:
        - clang --version
    - script:
        - cmake --version
    - stage: test
      script:
        - echo "Test stage"