language: cpp
compiler: clang
os: osx
osx_image: xcode10.2

jobs:
  include:
    # The build stage will build the library for Darwin, Android and iOS.
    - stage: build
      name: Darwin
      script: ./build.sh --darwin
    - script: echo "TODO Android build"
      name: Android
    - script: ./build.sh --ios
      name: iOS
    # The test stage will run all the tests and it will calculate the coverage.
    - stage: test
      script:
        - echo "Test stage"