#!/bin/bash

scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
projectDir=${scriptDir}
libName="nativemobile"
libTarget=${projectDir}/lib
libBuildDir=${projectDir}/build/lib
darwinBuildDir=${libBuildDir}/darwin
androidBuildDir=${libBuildDir}/android
iosBuildDir=${libBuildDir}/ios
iosFrameworkDir=${iosBuildDir}/framework
iosFrameworkFileName=${libName}.framework
iosUniversalFrameworkDir=${iosFrameworkDir}/universal

function notify_uncorrect_usage() {
    printf "Supported args:\n--darwin\n--android\n--ios\n--all\n"
    exit 1
}

function darwin() {
    echo "Building lib for this system..."
    cmake -B${darwinBuildDir} \
        -DBUILD_TESTS=OFF
    (cd ${darwinBuildDir} && make export-lib)
}

function android() {
    local abis=(armeabi-v7a arm64-v8a x86 x86_64)
    for abi in "${abis[@]}"; do
        build_android_abi ${abi}
    done
}

function build_android_abi() {
    local abi=$1
    local abiBuildDir=${androidBuildDir}/${abi}
    echo "Building Android shared lib for ABI $abi..."
    cmake -B${abiBuildDir} \
        -DBUILD_TESTS=OFF \
        -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
        -DCMAKE_SYSTEM_NAME=Android \
        -DANDROID_PLATFORM=android-16 \
        -DANDROID_ABI=${abi}

    (cd ${abiBuildDir} && make export-lib)
}

function ios() {
    echo "Building iOS shared lib..."
    cmake -B${iosBuildDir} -GXcode \
        -DBUILD_TESTS=OFF \
        -DCMAKE_SYSTEM_NAME=iOS \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=9.3

    build_universal_framework

    local libFilePath=${iosUniversalFrameworkDir}/${iosFrameworkFileName}
    local libSymPath=${PREBUILT_LIBS}/${libName}/ios
    mkdir -p "$libSymPath"
    ln -sf ${libFilePath} ${libSymPath}
}

function build_universal_framework() {
    local universalFramework=${iosUniversalFrameworkDir}/${iosFrameworkFileName}

    build_framework_for_sdk iphoneos
    build_framework_for_sdk iphonesimulator

    local phoneFramework=${iosFrameworkDir}/iphoneos/${iosFrameworkFileName}
    local simulatorFramework=${iosFrameworkDir}/iphonesimulator/${iosFrameworkFileName}

    rm -rf ${iosUniversalFrameworkDir}
    mkdir -p ${iosUniversalFrameworkDir}

    # Copy the files from the iphoneos framework to the universal one.
    cp -r ${phoneFramework}/. ${universalFramework}

    # Create the universal framework using the simulator and the phone framework.
    lipo ${simulatorFramework}/${libName} ${phoneFramework}/${libName} -create -output ${universalFramework}/${libName} | echo

    # Change the install name of the framework to avoid absolute paths.
    install_name_tool -id "@rpath/${iosFrameworkFileName}/$libName" ${universalFramework}/${libName}
}

function build_framework_for_sdk() {
    local sdk=$1

    # The target generated by CMake for ios is "lib-ios".
    (cd ${iosBuildDir} && xcodebuild -target lib-ios \
        -configuration "Release" \
        -UseModernBuildSystem=NO \
        -sdk ${sdk} \
        CONFIGURATION_BUILD_DIR=${iosFrameworkDir}/${sdk} \
        clean \
        build)
}

system=$1
[[ -z "$system" ]] && notify_uncorrect_usage

case $system in
"--darwin")
    darwin
    ;;
"--android")
    android
    ;;
"--ios")
    ios
    ;;
"--all")
    darwin
    android
    ios
    ;;
*)
    notify_uncorrect_usage
    ;;
esac
