# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/antoniolig/Developer/c++/native_mobile_lib/lib/CMakeLists.txt))

/Users/antoniolig/Developer/c++/native_mobile_lib/xcode_build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -H/Users/antoniolig/Developer/c++/native_mobile_lib -B/Users/antoniolig/Developer/c++/native_mobile_lib/xcode_build
